# Generated by Django 5.2 on 2025-04-22 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_departement', models.CharField(choices=[('DIRECTION', 'DIR'), ('RESSORCE HUMAINE', 'RH'), ('INFORMATIQUE', 'IT'), ('MARKETING', 'MARKET'), ('COMPTABILITE', 'COMPTA'), ('PRODUCTION', 'PROD')], default='RH')),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(choices=[('M', 'Monsieur'), ('F', 'Madame')], default='M', max_length=1)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(blank=True, max_length=250)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=10)),
                ('pays', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('numero_securite_sociale', models.CharField(blank=True, max_length=15)),
                ('date_embauche', models.DateField()),
                ('poste', models.CharField(max_length=100)),
                ('nom_diplome', models.CharField(max_length=100)),
                ('date_obtention_diplome', models.DateField()),
                ('type_caces', models.CharField(choices=[('R489-1A', 'Transpalettes à conducteur porté'), ('R489-1b', 'Gerbeurs à conducteur porté'), ('R489-cat-3', 'Chariots élévateur (6T)'), ('R489-cat-5', 'Chariots élévateurs à mât rétractable'), ('R482', 'Engin de chantier'), ('R490', 'Grues auxiliaires'), ('R486', 'Nacelle')], max_length=20)),
                ('date_obtention_caces', models.DateField()),
                ('date_expiration_caces', models.DateField()),
                ('type_permis', models.CharField(choices=[('A', 'A (Moto)'), ('B', 'B (Voiture)'), ('C', 'C (Poids lourd)'), ('D', 'D (Transport en commun)'), ('BE', 'BE (Voiture + Remorque)')], max_length=20)),
                ('date_obtention_permis', models.DateField()),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Stage', 'Stage'), ('Alternance', 'Alternance')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('departement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='ressource_humaine.departement')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
            ],
        ),
    ]
