# Generated by Django 5.2 on 2025-04-22 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ressource_humaine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departement',
            old_name='type_departement',
            new_name='nom_departement',
        ),
        migrations.RemoveField(
            model_name='departement',
            name='nom',
        ),
    ]
